name: CI/CD Pipeline

on: [push]

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Execute automation script
      run: |
        chmod +x automation.sh
        ./automation.sh 2>&1 | tee execution.log
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: execution.log
        retention-days: 7
