name: CI/CD Pipeline

on: [push]

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute automation script
        run: |
          chmod +x automation.sh
          ./automation.sh 2>&1 | tee execution.log

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: execution-logs
          path: execution.log
          retention-days: 7
